window.CAREER_DATA = {
  meta: {
    updated: "2026-10-04",
    note: "平台投递仅记录出现HR‘感兴趣/交换简历/简历合适’等正向信号的机会；未注明后续者，默认正向反馈后暂无进一步回复。"
  },
  applications: [
    {id:"app-001",company:"商务印书馆有限公司",role:"人力资源管理",city:"北京",salary:"",source:"国聘/单独网申",recruitType:"2027校招",employment:"正式全职",track:"文化出版/人力HR",status:"已投递",applied:"2026-09-28",lastContact:"",deadline:"",priority:"A",core:true,match:"中国出版集团体系；工商管理本科+两段国企综合/人事党群经历可转译。",risk:"需等待后续筛选。",next:"等待通知；如开放补充材料则及时跟进。",note:"",url:"https://www.iguopin.com/job/detail?id=218413998171750588"},
    {id:"app-002",company:"中国大百科全书出版社有限公司",role:"史宪工作室-编辑",city:"北京",salary:"",source:"国聘/单独网申",recruitType:"2027校招",employment:"正式全职",track:"文化出版/编辑内容",status:"已投递",applied:"2026-09-28",lastContact:"",deadline:"",priority:"S",core:true,match:"历史学硕士、史料整理与出版社编辑实习直接匹配。",risk:"北京岗位；竞争可能较强。",next:"重点等待笔试/面试通知。",note:"",url:""},
    {id:"app-003",company:"中国农业发展银行",role:"综合管理岗",city:"",salary:"",source:"单独网申",recruitType:"2027校招",employment:"正式全职",track:"综合管理",status:"已投递",applied:"2026-09-28",lastContact:"",deadline:"",priority:"B",core:false,match:"综合文字、管理本科、国企实习可迁移。",risk:"非核心行业；需看岗位地区与考试安排。",next:"等待筛选/笔试通知。",note:"",url:"https://applyjob.chinahr.com/page/job/success?projectId=6a8fd914f6bf3d0ac213dd5c"},
    {id:"app-004",company:"中国社会科学出版社",role:"人事专员",city:"北京",salary:"",source:"高校人才网/单独网申",recruitType:"2026招聘启事",employment:"正式全职",track:"文化出版/人力HR",status:"已投递",applied:"2026-09-24",lastContact:"",deadline:"",priority:"A",core:true,match:"出版社行业+人力综合经历，学历匹配。",risk:"具体流程/资格需等待反馈。",next:"等待通知。",note:"",url:"https://www.gaoxiaojob.com/member/person/delivery"},
    {id:"app-005",company:"中国社会科学出版社",role:"校对专员",city:"北京",salary:"",source:"高校人才网/单独网申",recruitType:"2026招聘启事",employment:"正式全职",track:"文化出版/编辑内容",status:"已投递",applied:"2026-09-04",lastContact:"",deadline:"",priority:"A",core:true,match:"出版社实习、文字校对与史料核验经历。",risk:"投递较早，暂无进一步回复。",next:"保持记录，不额外消耗精力。",note:"截图显示2026-09-04投递。",url:""},
    {id:"app-006",company:"中国社会科学出版社",role:"党群工作人员（老干部、工青妇）",city:"北京",salary:"",source:"高校人才网/单独网申",recruitType:"2026招聘启事",employment:"正式全职",track:"党群行政",status:"已投递",applied:"2026-09-04",lastContact:"",deadline:"",priority:"B",core:true,match:"两段国企党群经历高度相关。",risk:"可能存在政治面貌等硬性资格要求，需以后续审核为准。",next:"等待反馈。",note:"截图显示2026-09-04投递。",url:""},
    {id:"app-007",company:"中国社会科学出版社",role:"党群工作人员（党务、纪检）",city:"北京",salary:"",source:"高校人才网/单独网申",recruitType:"2026招聘启事",employment:"正式全职",track:"党群行政",status:"已投递",applied:"2026-09-04",lastContact:"",deadline:"",priority:"B",core:true,match:"党建材料、组织发展、会议材料等经历高度相关。",risk:"可能存在党员硬门槛。",next:"等待资格审核结果。",note:"截图显示2026-09-04投递。",url:""},
    {id:"app-008",company:"浙江文投",role:"人事专员/综合秘书",city:"杭州",salary:"",source:"高校人才网/单独网申",recruitType:"社招应届可投/待核",employment:"正式全职",track:"文化国企/人力HR/综合管理",status:"已投递",applied:"2026-09-24",lastContact:"",deadline:"",priority:"A",core:true,match:"文化国企+杭州；国企人力/综合材料经历可直接转译。",risk:"是否存在工作年限硬门槛需以岗位表为准。",next:"等待筛选；如收到反馈优先跟进。",note:"",url:"https://www.gaoxiaojob.com/member/person/delivery"},
    {id:"app-009",company:"中信兴业投资集团有限公司",role:"综合专员（党务方向）",city:"",salary:"",source:"51job/单独网申",recruitType:"2027校招",employment:"正式全职",track:"党群行政/综合管理",status:"已投递",applied:"2026-09-24",lastContact:"",deadline:"",priority:"B",core:false,match:"国企党群、综合文字与会务经验匹配。",risk:"行业不是核心兴趣方向。",next:"等待通知。",note:"",url:"https://xyz.51job.com/External/Others/JobsSelect.aspx?JobID=c1e72c4a-3d34-4c33-bbe1-2e77542c258e&CtmID=d7527e79-29e3-42ba-b0ce-dd5d3dc173e4&JobSelectType=0"},
    {id:"app-010",company:"中粮油脂控股有限公司",role:"优粮生计划-宣传综合岗",city:"",salary:"",source:"应届生/51job",recruitType:"2027校招",employment:"正式全职",track:"品牌传播/综合管理",status:"已投递",applied:"2026-09-23",lastContact:"",deadline:"",priority:"B",core:false,match:"宣传材料、企业文化与国企综合经历可迁移。",risk:"行业非核心兴趣。",next:"等待筛选。",note:"截图显示该岗位；CSV以‘中粮集团-宣传综合岗’记录。",url:""},
    {id:"app-011",company:"中粮集团有限公司",role:"优粮生计划-战略规划岗",city:"",salary:"",source:"应届生/51job",recruitType:"2027校招",employment:"正式全职",track:"综合管理/战略",status:"已投递",applied:"2026-09-23",lastContact:"",deadline:"",priority:"B",core:false,match:"工商管理本科+企业研究/材料能力。",risk:"战略岗位竞争和专业偏好需关注。",next:"等待筛选。",note:"",url:""},
    {id:"app-012",company:"中粮科工股份有限公司",role:"行政纪检专员",city:"",salary:"",source:"应届生/51job",recruitType:"2027校招",employment:"正式全职",track:"党群行政/综合管理",status:"已投递",applied:"2026-09-23",lastContact:"",deadline:"",priority:"B",core:false,match:"党群材料、行政和档案经历。",risk:"非核心行业。",next:"等待筛选。",note:"",url:""},
    {id:"app-013",company:"2027武汉选聘管培",role:"江汉关博物馆",city:"武汉",salary:"",source:"单独网申",recruitType:"2027选聘/管培",employment:"正式全职",track:"文博/综合管理",status:"已投递",applied:"2026-09-23",lastContact:"",deadline:"",priority:"S",core:true,match:"文博场景与历史学专业高度一致，武汉地域也有优势。",risk:"具体岗位职责与流程需等待通知。",next:"高优先级等待后续。",note:"",url:"https://wuhan.nomax.vip/tip/stdlogin.do?method=fwdLoginPage"},
    {id:"app-014",company:"中国能源建设集团广东火电工程有限公司",role:"党务管理岗",city:"广州",salary:"",source:"国聘/校招",recruitType:"2027校招",employment:"正式全职",track:"党群行政",status:"已投递",applied:"2026-09-23",lastContact:"",deadline:"",priority:"B",core:false,match:"两段国企党群实习高度相关。",risk:"地域与行业一般；政治面貌要求需以正式资格审核为准。",next:"等待通知。",note:"",url:"https://www.iguopin.com/job/detail?id=217447296680330524&project_id=215123984184772101"},
    {id:"app-015",company:"中国华能",role:"教研管理岗",city:"",salary:"",source:"单独网申",recruitType:"2027校招",employment:"正式全职",track:"研究/综合管理",status:"已投递",applied:"2026-09-23",lastContact:"",deadline:"",priority:"B",core:false,match:"研究训练、材料写作、项目整理能力。",risk:"具体单位/地点需补充。",next:"等待筛选。",note:"",url:"https://zhaopin.chng.com.cn/ManagementTraineeRecruit?positionId=2000229"},

    {id:"app-016",company:"中信出版集团",role:"校招-助理编辑（营销方向、策划方向）",city:"北京",salary:"9-12K",source:"BOSS",recruitType:"2027校招",employment:"正式全职",track:"文化出版/编辑内容",status:"交换简历",applied:"2026-09-16",lastContact:"2026-09-16",deadline:"",priority:"S",core:true,match:"历史硕士+出版社编辑实习+研究写作。",risk:"平台交换简历只是弱正向信号；暂无进一步回复。",next:"等待HR推进；遇到官方校招入口优先正式网申。",note:"正向反馈后暂无进一步回复。",url:""},
    {id:"app-017",company:"后浪出版社",role:"图书编辑",city:"北京",salary:"7-8K",source:"BOSS",recruitType:"平台机会",employment:"正式全职",track:"文化出版/编辑内容",status:"交换简历",applied:"2026-09-22",lastContact:"2026-09-22",deadline:"",priority:"A",core:true,match:"编辑实习与历史学训练直接相关。",risk:"平台互动未转化为正式面试。",next:"可低成本跟进一次，之后不反复追问。",note:"正向反馈后暂无进一步回复。",url:""},
    {id:"app-018",company:"七猫",role:"脑洞短篇小说责编（管培生）",city:"杭州",salary:"8-12K·14薪",source:"BOSS",recruitType:"校招/管培",employment:"正式全职",track:"编辑内容",status:"交换简历",applied:"2026-09-28",lastContact:"2026-09-28",deadline:"",priority:"A",core:false,match:"内容编辑、文字判断与读者意识可迁移。",risk:"网文内容生态与严肃出版差异较大。",next:"若HR继续推进再评估工作强度和内容价值。",note:"正向反馈后暂无进一步回复。",url:""},
    {id:"app-019",company:"外企德科数字技术有限公司",role:"HR（学习发展方向）",city:"杭州",salary:"8000-12000元",source:"BOSS",recruitType:"平台机会",employment:"正式全职",track:"人力HR/学习发展",status:"HR感兴趣",applied:"2026-10-03",lastContact:"2026-10-03",deadline:"",priority:"A",core:false,match:"人力实习+培训/材料/项目协调能力。",risk:"需核实实际用工主体、是否外包/派遣及工作内容。",next:"只有明确直签、职责合适再推进。",note:"正向反馈后暂无进一步回复。",url:""},
    {id:"app-020",company:"外企德科",role:"行政综合助理一（地产）",city:"杭州",salary:"1.2-1.5万",source:"BOSS",recruitType:"平台机会",employment:"正式全职/待核",track:"综合管理",status:"HR感兴趣",applied:"2026-09-22",lastContact:"2026-09-22",deadline:"",priority:"B",core:false,match:"行政综合、材料和协调经验。",risk:"需核实用工主体与是否派遣；地产条线非核心偏好。",next:"若再联系先问劳动合同主体。",note:"正向反馈后暂无进一步回复。",url:""},
    {id:"app-021",company:"中国人寿保险股份有限公司武汉市分公司",role:"行政人事专员",city:"武汉",salary:"5000-6000元",source:"BOSS",recruitType:"平台机会",employment:"正式全职/待核",track:"人力HR/综合管理",status:"HR感兴趣",applied:"2026-10-03",lastContact:"2026-10-03",deadline:"",priority:"C",core:false,match:"人力行政经历。",risk:"保险行业不在目标行业池；需警惕岗位是否带销售属性。",next:"非核心，除非职责纯后台且条件合适。",note:"正向反馈后暂无进一步回复。",url:""},
    {id:"app-022",company:"新城控股集团股份有限公司",role:"27届新睿管培生-新城吾悦",city:"武汉",salary:"1.3-1.6万·14薪",source:"51job/应届生",recruitType:"2027管培",employment:"正式全职",track:"管培/商业管理",status:"HR感兴趣",applied:"2026-09-22",lastContact:"2026-09-23",deadline:"",priority:"B",core:false,match:"管理本科、综合协调与项目经验。",risk:"商业地产节奏与轮岗压力需核实。",next:"若进入面试再做公司/岗位背调。",note:"多个新城吾悦主体均显示‘HR反馈简历合适’，按同一岗位族合并。",url:""},
    {id:"app-023",company:"上海招商局物业管理有限公司",role:"项目管理岗（2027届）",city:"上海",salary:"7-9.5千·14薪",source:"51job",recruitType:"2027校招",employment:"正式全职",track:"项目管理/综合管理",status:"HR感兴趣",applied:"2026-10-03",lastContact:"2026-10-03",deadline:"",priority:"B",core:false,match:"央企体系、项目协调与综合管理经历。",risk:"物业项目管理可能现场性强，工作节奏需核实。",next:"若进一步联系，重点问岗位日常、值班/周末和晋升路径。",note:"正向反馈后暂无进一步回复。",url:""},
    {id:"app-024",company:"上海太平洋房屋服务有限公司",role:"秋招26届 管培生 上海部",city:"上海",salary:"6千-1万",source:"51job",recruitType:"秋招/管培",employment:"正式全职/待核",track:"管培",status:"HR感兴趣",applied:"2026-09-22",lastContact:"2026-09-22",deadline:"",priority:"C",core:false,match:"管理背景。",risk:"房地产经纪/销售属性可能较强，不符合核心偏好。",next:"低优先级，不主动投入。",note:"正向反馈后暂无进一步回复。",url:""},
    {id:"app-025",company:"上海太平洋房屋服务有限公司",role:"本科优先 总部直招 可线上面试",city:"上海",salary:"9.5千-1.5万",source:"51job",recruitType:"平台机会",employment:"正式全职/待核",track:"其他",status:"HR感兴趣",applied:"2026-09-22",lastContact:"2026-09-22",deadline:"",priority:"C",core:false,match:"门槛宽。",risk:"岗位名称过泛，销售/经纪属性需警惕。",next:"非核心。",note:"正向反馈后暂无进一步回复。",url:""},
    {id:"app-026",company:"武汉泽国译民教育科技",role:"会议策划管培生",city:"福州",salary:"10-14K",source:"BOSS",recruitType:"平台机会",employment:"正式全职/待核",track:"项目/活动策划",status:"交换简历",applied:"2026-09-22",lastContact:"2026-09-22",deadline:"",priority:"C",core:false,match:"活动组织、项目协调、文字能力。",risk:"教育科技公司，地域与业务并非核心方向。",next:"无后续则自然归档。",note:"正向反馈后暂无进一步回复。",url:""},
    {id:"app-027",company:"联特科技",role:"企业文化应届生",city:"武汉",salary:"",source:"BOSS",recruitType:"校招",employment:"正式全职",track:"企业文化/品牌传播",status:"停止招聘",applied:"2026-09-28",lastContact:"2026-09-28",deadline:"",priority:"B",core:false,match:"企业文化、宣传材料经历匹配。",risk:"岗位已停止招聘。",next:"归档。",note:"曾交换简历；目前停止招聘。",url:""},
    {id:"app-028",company:"卓尔数科",role:"人力资源（J10243）",city:"武汉",salary:"",source:"BOSS",recruitType:"校招/平台机会",employment:"正式全职",track:"人力HR",status:"停止招聘",applied:"2026-09-07",lastContact:"2026-09-11",deadline:"",priority:"B",core:false,match:"招聘、培训、员工关系等与人力方向匹配。",risk:"岗位已停止招聘。",next:"归档。",note:"此前已沟通了解；当前停止招聘。",url:""},
    {id:"app-029",company:"杭州潮牌网络科技有限公司",role:"文理科文稿编辑（兼职）",city:"杭州",salary:"300-600元/天",source:"BOSS",recruitType:"兼职",employment:"兼职",track:"编辑内容",status:"交换简历",applied:"2026-09-23",lastContact:"2026-09-23",deadline:"",priority:"C",core:false,match:"文字编辑能力。",risk:"兼职，不计入本轮正式秋招主漏斗。",next:"默认隐藏于正式岗视图。",note:"",url:""},
    {id:"app-030",company:"吉安卓渠科技有限公司",role:"文章写作（全科均可）",city:"武汉",salary:"150-300元/天",source:"BOSS",recruitType:"兼职",employment:"兼职",track:"编辑内容",status:"HR感兴趣",applied:"2026-09-23",lastContact:"2026-09-23",deadline:"",priority:"C",core:false,match:"文字能力。",risk:"兼职，不纳入正式秋招漏斗。",next:"默认隐藏于正式岗视图。",note:"",url:""},
    {id:"app-031",company:"北京收纳熊生活服务",role:"收纳整理师",city:"北京",salary:"8-12K",source:"BOSS",recruitType:"平台机会",employment:"正式全职/待核",track:"其他/生活服务",status:"交换简历",applied:"2026-09-23",lastContact:"2026-09-23",deadline:"",priority:"C",core:false,match:"属于个人兴趣探索方向。",risk:"非本轮核心职业线。",next:"作为探索记录，不计入核心求职判断。",note:"正向反馈后暂无进一步回复。",url:""}
  ],
  hc: [
    {id:"hc-001",company:"中国教育出版传媒集团有限公司",role:"2027年应届高校毕业生公开招聘（所属出版单位多岗位）",city:"北京",track:"出版/文化央企",type:"2027应届公开招聘",published:"2026-09-29",deadline:"2026-10-21",priority:"S",status:"建议尽快投递",match:"历史学硕士与出版实习高度匹配；工商管理本科可覆盖部分综合管理方向。",risk:"需逐岗核对专业与岗位条件。",url:"https://jybzp.chsi.com.cn/home/bul/announcement/ymq873fg3ej1azdq"},
    {id:"hc-002",company:"中国出版集团有限公司",role:"2027届校园招聘（多岗位）",city:"北京/上海",track:"出版/文化央企",type:"校招正式岗",published:"2026-09-23",deadline:"2026-11-15",priority:"S",status:"已投递/部分岗位",match:"历史学、出版实习、文字研究与工商管理背景均可覆盖不同岗位。",risk:"每人可填职位有限，需做志愿优先级。",url:"https://cnpubg.iguopin.com/"},
    {id:"hc-003",company:"中信出版集团",role:"“璞玉计划”助理编辑/营销编辑等",city:"北京",track:"出版",type:"2027校招正式岗",published:"2026-09-01",deadline:"2026-12-31",priority:"S",status:"已投递/平台互动",match:"历史学硕士、出版实习、内容研究与文字能力匹配。",risk:"需要按岗位方向定制材料。",url:""},
    {id:"hc-004",company:"外语教学与研究出版社",role:"市场助理等校招岗位",city:"北京",track:"出版",type:"2027秋招正式岗",published:"2026-09-21",deadline:"2026-11-15",priority:"B",status:"待评估",match:"出版社实习、本科工商管理、文化内容理解。",risk:"部分岗位偏市场而非编辑。",url:"http://hr.fltrp.com/campus"},
    {id:"hc-005",company:"华数传媒控股",role:"2027校招相关岗位",city:"杭州",track:"国企传媒",type:"2027校招正式岗",published:"2026-09-01",deadline:"2026-10-20",priority:"B",status:"待评估",match:"杭州、国企传媒平台；可关注综合/内容/项目岗位。",risk:"现有明确岗位可能偏技术。",url:"https://wasu.hotjob.cn"}
  ],
  watch: [
    {company:"中国出版集团及旗下商务印书馆、中华书局、三联、人文等",city:"北京/上海",type:"出版央企",why:"严肃出版、知识壁垒高、稳定读者群。",targets:"编辑、策划、综合管理、人力"},
    {company:"中信出版集团",city:"北京",type:"出版国企",why:"知识内容品牌、财经社科受众稳定。",targets:"助理编辑、内容策划、营销编辑"},
    {company:"上海世纪出版集团及旗下出版社",city:"上海",type:"出版国企",why:"上海核心出版体系。",targets:"编辑、策划、发行、综合管理"},
    {company:"浙江出版联合集团及旗下出版社",city:"杭州",type:"出版国企",why:"杭州本地、出版体系完整。",targets:"编辑、策划、综合管理"},
    {company:"西泠印社集团",city:"杭州",type:"文化国企/艺术收藏",why:"艺术、收藏、老字号与高文化资本受众。",targets:"编辑、品牌、文化项目、综合管理"},
    {company:"朵云轩",city:"上海",type:"国有文化/艺术收藏",why:"书画艺术、收藏和老字号属性明显。",targets:"艺术项目、品牌、综合管理"},
    {company:"荣宝斋",city:"北京",type:"文化央企/艺术收藏",why:"书画、文房、拍卖、出版与非遗。",targets:"编辑、文化项目、品牌、综合管理"},
    {company:"保利文化/保利拍卖/保利工艺",city:"北京/上海等",type:"央企文化/艺术品",why:"艺术品、演艺、收藏业务高壁垒。",targets:"文化项目、拍卖运营、品牌、综合管理"},
    {company:"中国唱片集团",city:"北京/上海等",type:"文化央企/音乐",why:"音乐内容、版权与文化资产属性。",targets:"内容、版权、品牌、综合管理"},
    {company:"故宫出版社",city:"北京",type:"文博出版",why:"文博内容与出版结合。",targets:"编辑、策划、文创、文化传播"},
    {company:"上海市历史博物馆（上海革命历史博物馆）",city:"上海",type:"文博事业单位",why:"近现代史、城市史与公共历史传播高度匹配。",targets:"研究、文博宣传、教育活动、公共历史传播"},
    {company:"中国丝绸博物馆",city:"杭州",type:"文博/非遗/艺术",why:"杭州本地；丝绸史、传统工艺、时尚与文化交叉。",targets:"社会教育、国际交流、陈列展览、文化项目"},
    {company:"中国文化传媒集团",city:"北京",type:"文化央企/媒体/艺术",why:"艺术、文旅、非遗、媒体和研究业务交叉。",targets:"文化项目、品牌传播、研究/综合管理"},
    {company:"中国对外文化集团",city:"北京/深圳等",type:"文化央企/演艺会展",why:"国际演艺、艺术会展与文化交流资源壁垒高。",targets:"文化项目、艺术会展、品牌、综合管理"},
    {company:"上影集团/上海美术电影制片厂",city:"上海",type:"国企影视/IP",why:"经典文化IP与内容产业结合。",targets:"资料研究、项目策划、文案、新媒体、IP文化项目"}
  ]
};